name: TrabalhoPratico-Automacao

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe uma linha
        run: echo Hello, world!
      - name: Exibe duas linhas
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
